// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZjPDUNsSXXM9gg2Rh2t4erMEXJsr95Q8',
    appId: '1:56600216706:web:a214739bdf3d044236e09b',
    messagingSenderId: '56600216706',
    projectId: 'proyecto-ia-dieta',
    authDomain: 'proyecto-ia-dieta.firebaseapp.com',
    storageBucket: 'proyecto-ia-dieta.firebasestorage.app',
    measurementId: 'G-NXB7Q09L8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNiaYSq5XREspDijcTVeWJUCrB9QI-KJI',
    appId: '1:56600216706:android:6586e6bbf1acff6d36e09b',
    messagingSenderId: '56600216706',
    projectId: 'proyecto-ia-dieta',
    storageBucket: 'proyecto-ia-dieta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-PQc0sN0cy8UDODFCf3-zCn__gT1DUTA',
    appId: '1:56600216706:ios:ae9d94d7693b368f36e09b',
    messagingSenderId: '56600216706',
    projectId: 'proyecto-ia-dieta',
    storageBucket: 'proyecto-ia-dieta.firebasestorage.app',
    iosClientId:
        '56600216706-27vjkg7k2al5h1steo8dg25rvu97ogkv.apps.googleusercontent.com',
    iosBundleId: 'com.example.recomendacionDieta',
  );
}
